all:
  children:
    phase1:
      hosts:
        pa-test-eu-central-2-1:
          ansible_host: 10.160.160.12
          instance_id: i-00582f98275000f24
          target_group_arn: arn:aws:elasticloadbalancing:eu-central-2:072001649308:targetgroup/test-gwlb-tgrp/00bbf07d22294526e7
          region: eu-central-2
    phase2:
      hosts:
        fw-eu-central-1-1:
          ansible_host: 192.168.2.10
          instance_id: i-0abcdef1234567891
          target_group_arn: arn:aws:elasticloadbalancing:eu-central-1:123456789012:targetgroup/fw-gwlb-tg/abcd1234efgh5679
          region: eu-central-1
        fw-eu-central-1-2:
          ansible_host: 192.168.2.11
          instance_id: i-0abcdef1234567893
          target_group_arn: arn:aws:elasticloadbalancing:eu-central-1:123456789012:targetgroup/fw-gwlb-tg/abcd1234efgh5680
          region: eu-central-1

    # Repeat for phases 3 through 10

